# wrangler.toml
name = "miniplayportal"
compatibility_flags = ["nodejs_compat"]

[build]
command = "npm run pages:build"
cwd = "."
upload_format = "service-worker"

[build.upload]
dir = ".vercel/output/static"  # ← 이게 핵심!
